In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"D:\mahmoud\depi\Titanic.csv")
type(df)

pandas.core.frame.DataFrame

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
print (df.head())
print(df.tail())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

In [6]:
df.drop(['PassengerId', 'Name', 'Ticket'],axis=1,inplace=True)

In [8]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [9]:
def drop_cols(df,cols):
    return df.drop(columns=cols)

In [10]:
df=pd.read_csv(r"D:\mahmoud\depi\Titanic.csv")

In [11]:
cols=['PassengerId', 'Name', 'Ticket']
df=drop_cols(df,cols)

In [12]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [14]:
dtypes=df.dtypes
nunique=df.nunique()
pd.DataFrame({'dtypes':dtypes,'nunique':nunique}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,int64,int64,object,float64,int64,int64,float64,object,object
nunique,2,3,2,88,7,7,248,147,3

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object
 8   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [17]:
cat_cols = ['Survived', "Pclass", "Sex", "SibSp", "Parch", "Embarked"]
df[cat_cols]=df[cat_cols].astype('category')

In [18]:
df

    Survived Pclass     Sex   Age SibSp Parch     Fare Cabin Embarked
0          0      3    male  22.0     1     0   7.2500   NaN        S
1          1      1  female  38.0     1     0  71.2833   C85        C
2          1      3  female  26.0     0     0   7.9250   NaN        S
3          1      1  female  35.0     1     0  53.1000  C123        S
4          0      3    male  35.0     0     0   8.0500   NaN        S
..       ...    ...     ...   ...   ...   ...      ...   ...      ...
886        0      2    male  27.0     0     0  13.0000   NaN        S
887        1      1  female  19.0     0     0  30.0000   B42        S
888        0      3  female   NaN     1     2  23.4500   NaN        S
889        1      1    male  26.0     0     0  30.0000  C148        C
890        0      3    male  32.0     0     0   7.7500   NaN        Q

[891 rows x 9 columns]

In [19]:
dtypes = df.dtypes
nunique = df.nunique()
pd.DataFrame({"dtypes": dtypes, "nunique": nunique}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,category,category,category,float64,category,category,float64,object,category
nunique,2,3,2,88,7,7,248,147,3

In [24]:
def get_type_info(df):
    return pd.DataFrame({'dtypes':df.dtypes,'nunique':df.nunique()}).T

In [25]:
get_type_info(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,category,category,category,float64,category,category,float64,object,category
nunique,2,3,2,88,7,7,248,147,3

In [26]:
df.select_dtypes('category')

    Survived Pclass     Sex SibSp Parch Embarked
0          0      3    male     1     0        S
1          1      1  female     1     0        C
2          1      3  female     0     0        S
3          1      1  female     1     0        S
4          0      3    male     0     0        S
..       ...    ...     ...   ...   ...      ...
886        0      2    male     0     0        S
887        1      1  female     0     0        S
888        0      3  female     1     2        S
889        1      1    male     0     0        C
890        0      3    male     0     0        Q

[891 rows x 6 columns]

In [28]:
null=df.isnull().sum()
print(null)
ratio = (null / 891) * 100
ratio

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Fare         0.000000
Cabin       77.104377
Embarked     0.224467
dtype: float64

In [29]:
df = df.dropna(subset=['Embarked'])

In [31]:
df=df.drop('Cabin',axis=1)

In [32]:
df.describe()

              Age        Fare
count  712.000000  889.000000
mean    29.642093   32.096681
std     14.492933   49.697504
min      0.420000    0.000000
25%     20.000000    7.895800
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [35]:
median=df['Age'].median()
print(median)

28.0

In [36]:
df['Age']=df["Age"].fillna(median,inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_21848\2793265777.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age']=df["Age"].fillna(median,inplace=True)

In [37]:
null = df.isnull().sum()
ratio = (null / 891) * 100
pd.DataFrame({"null": null, "ratio": ratio})

          null      ratio
Survived     0   0.000000
Pclass       0   0.000000
Sex          0   0.000000
Age        889  99.775533
SibSp        0   0.000000
Parch        0   0.000000
Fare         0   0.000000
Embarked     0   0.000000

In [39]:
num_col=df.select_dtypes('number').columns
num_col
for col in num_col:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    print(Q1, Q3)
    IQR = Q3 - Q1
    print("IQR:", IQR)
    lower_fence = Q1 - 1.5 * IQR
    upper_fence = Q3 + 1.5 * IQR
    print(lower_fence, upper_fence)

7.8958 31.0
IQR: 23.1042
-26.7605 65.6563

In [40]:
df.describe()

             Fare
count  889.000000
mean    32.096681
std     49.697504
min      0.000000
25%      7.895800
50%     14.454200
75%     31.000000
max    512.329200